spring.application.name=ElRecetarioDeShirBackend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

app.media.storage.root=${MEDIA_STORAGE_ROOT}

app.admin.bootstrap.enabled=${ADMIN_BOOTSTRAP_ENABLED:false}
app.admin.bootstrap.username=${ADMIN_BOOTSTRAP_USERNAME:}
app.admin.bootstrap.password=${ADMIN_BOOTSTRAP_PASSWORD:}
